
- hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap and sanity checks
      import_tasks:
        file: bootstrap.yml

    - name: USING VAULT
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/service/brage/utvikle:db_password auth_method=approle role_id=brage-client-utvikle secret_id=4000d88d-4440-b8fe-6406-d51571fe93be url=https://vault.bibsys.no:8200') }}"
      delegate_to: localhost

    - name: Create local.cfg
      template:
        src: local.cfg.j2
        dest: "{{ jenkins_workspace }}/dspace/config/local.cfg"
      delegate_to: localhost

    - name: Notify Slack
      slack:
        channel: "{{ SlackConfig.channel }}"
        icon_emoji: "{{ SlackConfig.icon }}"
        msg: "`[{{kunde}}]` Starter bygging: {{ kundedata[kunde]['arkivnavn'] | default('Brage') }}"
        token: "{{ SlackConfig.token }}"
        username: "{{ SlackConfig.sender }}"
      delegate_to: localhost
      when: fase == "produksjon"
