
- hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap and sanity checks
      import_tasks:
        file: bootstrap.yml

    - name: USING pcb
      vars:
        pcb: "pcb"
      debug:
        msg: "{{ secret }} arne {{ pcb }}"

#    - name: USING VAULT
#      debug:
#        msg: "{{ lookup('hashi_vault', 'secret=secret/service/brage/dev:db_password auth_method=approle role_id=brage-client-dev secret_id=9aa18444-077c-19a0-f889-277d621def1a url=https://vault.bibsys.no:8200')}}"

    - name: Create local.cfg
      template:
        src: local.cfg.j2
        dest: "{{ jenkins_workspace }}/dspace/config/local.cfg"
      delegate_to: localhost

    - name: Notify Slack
      slack:
        channel: "{{ SlackConfig.channel }}"
        icon_emoji: "{{ SlackConfig.icon }}"
        msg: "`[{{kunde}}]` Starter bygging: {{ kundedata[kunde]['arkivnavn'] | default('Brage') }}"
        token: "{{ SlackConfig.token }}"
        username: "{{ SlackConfig.sender }}"
      delegate_to: localhost
      when: fase == "produksjon"
