
- hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap and sanity checks
      import_tasks:
        file: bootstrap.yml

    - name: USING VAULT
      vars:
        db_password: lookup('hashi_vault', 'secret=secret/service/brage/dev:db_password auth_method=approle role_id=brage-client-dev secret_id={{ vault_secret }} url=https://vault.bibsys.no:8200')
      debug:
        msg: "db_password = {{ db_password }}"

    - name: Create local.cfg
      template:
        src: local.cfg.j2
        dest: "{{ jenkins_workspace }}/dspace/config/local.cfg"
      delegate_to: localhost

    - name: Notify Slack
      slack:
        channel: "{{ SlackConfig.channel }}"
        icon_emoji: "{{ SlackConfig.icon }}"
        msg: "`[{{kunde}}]` Starter bygging: {{ kundedata[kunde]['arkivnavn'] | default('Brage') }}"
        token: "{{ SlackConfig.token }}"
        username: "{{ SlackConfig.sender }}"
      delegate_to: localhost
      when: fase == "produksjon"
