
- hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap and sanity checks
      import_tasks:
        file: bootstrap.yml

    - name: Create local.cfg
      template:
        src: local.cfg.j2
        dest: "{{ jenkins_workspace }}/dspace/config/local.cfg"
      delegate_to: localhost

    - name: Notify Slack
      slack:
        channel: "{{ SlackConfig.channel }}"
        icon_emoji: "{{ SlackConfig.icon }}"
        msg: "`[{{kunde}}]` Starter bygging: {{ kundedata[kunde]['arkivnavn'] | default('Brage') }}"
        token: "{{ SlackConfig.token }}"
        username: "{{ SlackConfig.sender }}"
      delegate_to: localhost
      when: fase == "produksjon"
